---
title: "Data checks"
author: "Stefano Coretta"
format: html
---

## Beta not Gaussian

```{r}
#| label: setup

library(tidyverse)
library(coretta2018itaegg)
library(Hmisc)
library(brms)
```

```{r}
set.seed(8923)
x <- rbeta(1000, 4, 0.5)

plot(density(x))

bg <- brm(
  x ~ 1,
  data = data.frame(x),
  file = "data/cache/bg"
)

pp_check(bg, ndraws = 10)

bb <- brm(
  x ~ 1,
  family = Beta,
  data = data.frame(x),
  file = "data/cache/bb"
)

pp_check(bb, ndraws = 10)
```


## Voicing within closure

```{r}
#| label: load-ita-egg
#| 
data("ita_egg")
```

```{r}
ita_egg |> 
  ggplot(aes(voi_clo_prop)) +
  geom_density()

ita_egg |> 
  filter(voi_clo_prop > 0, voi_clo_prop < 1) |> 
  ggplot(aes(voi_clo_prop)) +
  geom_density() +
  geom_rug()
```

```{r}
ita_egg_filt <- ita_egg |> 
  filter(voi_clo_prop > 0, voi_clo_prop < 1)
```

```{r}
ita_egg_filt |> 
  ggplot(aes(vowel, voi_clo_prop)) +
  geom_jitter(alpha = 0.1, width = 0.2) +
  stat_summary(fun.data = "mean_cl_boot")
```

```{r}
ita_egg_filt |> 
  ggplot(aes(vowel, voi_clo_prop)) +
  geom_jitter(alpha = 0.2, width = 0.2, aes(colour = vowel)) +
  stat_summary(fun.data = "mean_cl_boot") +
  facet_grid(cols = vars(c2))
```

```{r}
ita_egg_filt |> 
  ggplot(aes(vowel, voi_clo_prop)) +
  stat_summary(fun.data = "mean_cl_boot") +
  facet_grid(cols = vars(c2))
```


```{r}
ita_egg_filt |> 
  ggplot(aes(speech_rate, voi_clo_prop)) + 
  geom_point(alpha = 0.5) +
  geom_smooth(method = "lm") +
  facet_wrap(vars(vowel))
```

## Vowel nasalisation

```{r}
#| label: read-nasal
nasal <- read_csv("https://raw.githubusercontent.com/ChristopherCarignan/journal-articles/refs/heads/master/rtMRI-velum/velum_data.csv") |> 
  filter(
    stress == "N",
    vowel %in% c("a_", "E_", "I_", "O_", "U_")
  ) |> 
  mutate(
    voicing = case_when(
      post %in% c("nt__", "nt_@", "nt_6", "nt_a") ~ "voiceless",
      post %in% c("nd_@", "nd_6", "nd_a") ~ "voiced"
    ),
    vowel = str_to_lower(vowel) |> str_remove("_")
  ) |> 
  # drop codas not included in the analysis
  drop_na(voicing) |> 
  mutate(
    nas_dur = (Vokal_off - velumopening_maxvel_on) * 1000,
    nas_prop = nas_dur / (Vokal_dur * 1000),
    NC = ifelse(voicing == "voiceless", "nt", "nd")
  ) |> 
  # drop observations with wrong fMRI tracking
  filter(nas_prop > 0, nas_prop < 1) |> 
  select(
    speaker, label, vowel, NC, voicing, nas_prop
  )

write_csv(nasal, "data/carignan2021/nasal.csv")
```

```{r}
nasal |> 
  ggplot(aes(nas_prop, fill = voicing)) +
  geom_density(alpha = 0.5)
```

```{r}
nasal |> 
  ggplot(aes(nas_prop, fill = voicing)) +
  geom_density(alpha = 0.5) +
  facet_wrap(~vowel)
```

